### ISSUE TITLE
Use a union for the data stored by a Json object

### ISSUE THREAD

**Issue by Tishj** [Abdi-29/new_json#1]
Since you only ever utilize the space of one of these variables, a union makes a lot of sense here :D

```c++
union JSONValue {
bool _bool,
int64_t _int,
uintptr_t _ptr //list pointer, or maybe even a string*
};
```

**Comment by Abdi-29** [comment]
thanks Tishj! I will have a look at it in morning

**Comment by Abdi-29** [comment]
```c
        struct values
	{
		values() {}
		jsonList	*list;
		jsonObject	object;
		std::string str;
		int			number;
		bool		boolean;
		~values() {}
	}		values;```


I had this one as union at first but the segment fault somehow

**Comment by Tishj** [comment]
I think the union members have to be POD
So in this case putting a std::string in there would be the problem if my assumption is correct

I fixed this in mine by storing a pointer to a string instead

**Comment by Abdi-29** [comment]
yep I was getting problem because std::string wasn't a pointer

**Comment by mraasvel** [comment]
A union can have non-POD types.
At least from C++ 11: https://en.cppreference.com/w/cpp/language/union
> If members of a union are classes with user-defined constructors and destructors, to switch the active member, explicit destructor and placement new are generally needed: 

This is fine since you are tracking the type but you would have to manually (explicitly) call the appropriate destructor based on the type. See how I implemented it and also [variant](https://en.cppreference.com/w/cpp/utility/variant) which I haven't used but looks to be the STL implementation of a [tagged union](https://en.wikipedia.org/wiki/Tagged_union).

**Comment by Tishj** [comment]
Did you mean "can have non-POD types" ?

**Comment by mraasvel** [comment]
Yeah, I edited it after posting it but I guess the email didn't update, btw you posted the whole email haha, at least the addresses are censored

**Comment by Tishj** [comment]
Good thing that's the first (and last) time I used that feature o.o wtf

**Comment by mraasvel** [comment]
Free outlook advertisement hahaha

**Comment by Abdi-29** [comment]
#[f8a2417](https://github.com/Abdi-29/new_json/commit/f8a24177aba837c95dbfa4fc018f86e507ca7385) fixes the issue! @Tishj @mraasvel

**Comment by mraasvel** [comment]
Good job! But don't forget that the constructors of classes in a union aren't called.

**Comment by Tishj** [comment]
You have to explicitly call the right destructor :)
